# Quiz 1

In [1]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [3]:
import numpy as np
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [4]:
a3.shape == a4.shape

False

In [5]:
a1.shape == a2.shape

False

In [6]:
a5.shape == a1.shape

True

In [7]:
a4.ndim() == 1

TypeError: 'int' object is not callable

In [9]:
a5.shape

(4,)

In [10]:
old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [12]:
old = np.array([[1, 1, 1], [1, 1, 1]])
print(old)

[[1 1 1]
 [1 1 1]]


In [14]:
new = old
print(new)

[[1 1 1]
 [1 1 1]]


In [16]:
new[0, :2] = 0

In [17]:
print(new)
print(old)

[[0 0 1]
 [1 1 1]]
[[0 0 1]
 [1 1 1]]


In [21]:
old[0,1]

0

In [23]:
import re 
s = 'ACBCAC'
print(
re.findall('^[AC]', s))

['A']


In [25]:
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
print(L)

5


In [26]:
x ='''Office of Research Administration: (734) 647-6333 | 4325 North Quad
Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205
Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500
Office of the Dean: (734) 647-3576 | 4322 North Quad
UMSI Engagement Center: (734) 763-1251 | 777 North University
Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad'''
print(x)

Office of Research Administration: (734) 647-6333 | 4325 North Quad
Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205
Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500
Office of the Dean: (734) 647-3576 | 4322 North Quad
UMSI Engagement Center: (734) 763-1251 | 777 North University
Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad


In [28]:
re.findall('\d{3}[-]\d{3}[-]\d{4}', x)


[]

In [29]:
re.findall('[(]\d{3}[)]\d{3}[-]\d{4}', x)


[]

In [30]:
re.findall('\d{3}\s\d{3}[-]\d{4}', x)


[]

In [31]:
re.findall('[(]\d{3}[)]\s\d{3}[-]\d{4}', x)


['(734) 647-6333',
 '(734) 647-8044',
 '(734) 763-2285',
 '(734) 647-3576',
 '(734) 763-1251',
 '(734) 764-9376']

In [32]:
x = 'I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'

In [33]:
re.findall('(?<=https:\/\/)([.]*)', x)

['']

In [34]:
re.findall('(?<=https:\/\/)([A-Za-z0-9]*)', x)

['google']

In [35]:
re.findall('(?<=[https]:\/\/)([A-Za-z0-9.]*)', x)

['google.com', 'www.baidu.com']

In [36]:
re.findall('(?<=https:\/\/)([A-Za-z0-9.]*), x)

SyntaxError: EOL while scanning string literal (<ipython-input-36-2f5f008d2c2c>, line 1)

In [37]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''


In [40]:
print(len(re.findall('\(.\)',text)))

4


In [41]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [47]:
a = np.random.rand(20,20)
b = np.random.rand(20,20)


In [48]:
l2_dist(a.T, b.T)

8.26383709680519

In [49]:

l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))

8.26383709680519

In [50]:

l2_dist(a, b)

8.26383709680519

In [52]:
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20, 1)))

160.83520014999021

# Quiz 2

In [1]:
import pandas as pd
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj1 = pd.Series(sdata)
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj2 = pd.Series(sdata, index=states)
obj3 = pd.isnull(obj2)

In [2]:
obj3['California']

True

In [3]:
obj2['California'] == None

False

In [4]:
import math
math.isnan(obj2['California'])

True

In [5]:
x = obj2['California']
obj2['California'] != x

True

In [6]:
import pandas as pd
d = {'1': 'Alice',
     '2': 'Bob',
     '3': 'Rita',
     '4': 'Molly',
     '5': 'Ryan'}
S = pd.Series(d)

In [12]:
#S.iloc[0:2]


S.iloc[0:3]


#S.loc[0:3]


#S.loc[0:2]

1    Alice
2      Bob
3     Rita
dtype: object

In [13]:
s1 = pd.Series({1: 'Alice', 2: 'Jack', 3: 'Molly'})
s2 = pd.Series({'Alice': 1, 'Jack': 2, 'Molly': 3})

In [14]:

s2.iloc[1]

2

In [15]:

s2.loc[1]

KeyError: 1

In [16]:
s1.loc[1]

'Alice'

In [17]:

s2[1]

2

In [30]:
s1.append(s2)

1        Alice
2         Jack
3        Molly
Alice        1
Jack         2
Molly        3
dtype: object

In [31]:
s1

1    Alice
2     Jack
3    Molly
dtype: object

In [20]:
s2.iteritems()

In [26]:
d = {'gre score': [337, 324, 316, 322,314], 'toefl score': [118, 107,104,110,103]}
df = pd.DataFrame(data=d)

In [29]:
df.where(df['toefl score'] > 105)

gre score  toefl score
0      337.0        118.0
1      324.0        107.0
2        NaN          NaN
3      322.0        110.0
4        NaN          NaN

In [32]:

df[(df['toefl score'].isin(range(106, 115)))]

gre score  toefl score
1        324          107
3        322          110

In [33]:

(df['toefl score'] > 105) & (df['toefl score'] < 115)

0    False
1     True
2    False
3     True
4    False
Name: toefl score, dtype: bool

In [34]:

df[(df['toefl score'] > 105) & (df['toefl score'] < 115)]

gre score  toefl score
1        324          107
3        322          110

In [35]:

df[df['toefl score'].gt(105) & df['toefl score'].lt(115)]

gre score  toefl score
1        324          107
3        322          110

In [37]:
array =  {'Name': ["Alice", "Jack"], 'Age': [20,22], 'Gender': ["f","m"]}
df1 = pd.DataFrame(data=array)

In [42]:

df1.iloc[0]

Name      Alice
Age          20
Gender        f
Name: 0, dtype: object

In [44]:

df1.T[0]

Name      Alice
Age          20
Gender        f
Name: 0, dtype: object

# Quiz 3

In [62]:
import pandas as pd
df = pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'], index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 'ok', 'ok', 'ok', 'poor', 'poor'], columns = ['Grades'])
my_categories= (my_categories=['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'], ordered=True)
grades = df['Grades'].astype(my_categories)
result = grades[(grades>'B') & (grades<'A')]
result

SyntaxError: invalid syntax (<ipython-input-62-9fe781354776>, line 3)

In [63]:
import pandas as pd
df = pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'], index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 'ok', 'ok', 'ok', 'poor', 'poor'], columns = ['Grades'])
my_categories = pd.CategoricalDtype(categories=['D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+'])
grades = df['Grades'].astype(my_categories)
result = grades[(grades>'B') & (grades<'A')]
result

TypeError: Unordered Categoricals can only compare equality or not

In [61]:
import pandas as pd
df = pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'], index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 'ok', 'ok', 'ok', 'poor', 'poor'], columns = ['Grades'])
my_categories= pd.CategoricalDtype(categories=['D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+'], ordered=True)
grades = df['Grades'].astype(my_categories)
result = grades[(grades>'B') & (grades<'A')]
result

excellent    A-
good         B+
Name: Grades, dtype: category
Categories (11, object): ['D' < 'D+' < 'C-' < 'C' ... 'B+' < 'A-' < 'A' < 'A+']

In [64]:
import pandas as pd
df = pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'], index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 'ok', 'ok', 'ok', 'poor', 'poor'], columns = ['Grades'])
my_categories = pd.CategoricalDtype(categories=['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'])
grades = df['Grades'].astype(my_categories)
result = grades[(grades>'B') & (grades<'A')]
result

TypeError: Unordered Categoricals can only compare equality or not

In [46]:
import pandas as pd
(pd.Timestamp('11/29/2019') + pd.offsets.MonthEnd()).weekday()

5

In [47]:
pd.Period('01/12/2019', 'M') + 5

Period('2019-06', 'M')

In [1]:
import numpy as np

a = np.arange(8)
b = a[4:6]
b[:] = 40
c = a[4] + a[6]
c

46

In [2]:
import re
s = 'ABCAC'

In [3]:
len(re.split('A', s)) == 2

False

In [4]:
bool(re.match('A', s)) == True


True

In [5]:
len(re.search('A', s)) == 2

TypeError: object of type 're.Match' has no len()

In [6]:
re.match('A', s) == True

False

# Quiz 4

In [26]:
def result():
    s = 'ACAABAACAAABACDBADDDFSDDDFFSSSASDAFAAACBAAAFASD'

    result = []
    # compete the pattern below
    pattern = r'([B-Z])[AAA]'
    for item in re.finditer(pattern, s):
      # identify the group number below.
      result.append(item.group())
      
    return result
result()

['CA', 'BA', 'CA', 'BA', 'BA', 'SA', 'DA', 'FA', 'BA', 'FA']

In [31]:
re.findall('[B-Z](?=AAA)','ACAABAACAAABACDBADDDFSDDDFFSSSASDAFAAACBAAAFASD' )

['C', 'F', 'B']

In [34]:
import pandas as pd
df = pd.Series({'d': 4, 'b': 7, 'a':-5 ,'c': 3})
df

d    4
b    7
a   -5
c    3
dtype: int64

In [40]:
s1 = pd.Series({'Mango': 20, 'Strawberry': 15, 'Blueberry':18 ,'Vanilla': 31})
s2 = pd.Series({'Strawberry': 20, 'Vanilla': 30, 'Banana':15 ,'Mango': 31, 'Plain':20})
s3 = s1.add(s2)
s3

Banana         NaN
Blueberry      NaN
Mango         51.0
Plain          NaN
Strawberry    35.0
Vanilla       61.0
dtype: float64

In [41]:
s3['Mango'] >=  s1.add(s2, fill_value = 0)['Mango']

True

In [42]:
s3['Plain'] >= s3['Mango']

False

In [43]:
s3['Blueberry'] == s1.add(s2, fill_value = 0)['Blueberry']

False

In [44]:
s3['Blueberry'] == s1.add(s2, fill_value = 0)['Blueberry']

False

In [45]:
S = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])

In [46]:
S['b':'e']

b    1
c    2
d    3
e    4
dtype: int32

In [47]:
S[['b', 'c', 'd']]

b    1
c    2
d    3
dtype: int32

In [48]:
S[S <= 3][S > 0]

b    1
c    2
d    3
dtype: int32

In [49]:
S[1:4]

b    1
c    2
d    3
dtype: int32

In [53]:
df = pd.DataFrame(data={'a': [5,5,71,67],
                        'b': [6,82,31,37],
                        'c': [20,28,92,49],
                        'i': ['R1','R2','R3','R4']}).set_index('i')
df

KeyError: "None of ['R1', 'R2', 'R3', 'R4'] are in the columns"

In [54]:
f = lambda x: x.max() + x.min()
df_new = df.apply(f)
df_new

a     76
b     88
c    112
dtype: int64

In [55]:
df_new[1]

88

In [58]:
df = pd.DataFrame(data={'Item': ['Item_1','Item_1','Item_1','Item_2','Item_2','Item_2'],
                        'Store': ['A','B','C','A','B','C'],
                        'Quantity sold': [10,20,None,5,10,15]})
df

Item Store  Quantity sold
0  Item_1     A           10.0
1  Item_1     B           20.0
2  Item_1     C            NaN
3  Item_2     A            5.0
4  Item_2     B           10.0
5  Item_2     C           15.0

In [59]:
df.groupby('Item').sum().iloc[0]['Quantity sold']

30.0